name: CreeperSpawn
version: 1.0
author: Jishnu
main: me.Jishnu.CreeperSpawn.Main
description: Spawns 10 Creepers on Player

commands:
  creepspawn:
    aliases: [cs]
    description: /cs to spawn 10 creepers